### ISSUE TITLE
Can not read some code in example

### ISSUE THREAD

**Issue by dblanchet** [PierreQuentel/cours_python#24]
Because one of the font colors is the same than the slide background, some chars can not be read when the code goes beyond it dedicated frame.

<img width="755" alt="capture d ecran 2017-04-28 a 11 03 58" src="https://cloud.githubusercontent.com/assets/845542/25522217/67b82d3c-2c02-11e7-96ca-ac193e62b3e2.png">

I'm not sure about the best way(s) to solve this issue:

- Do not use same color (e.g. change font color to light gray)
- Enforce code wrapping in frame.
- Other solution?

**Comment by PierreQuentel** [comment]
Merci David !

In commit 7d1479d7ff7b074c41e8d04e991bc572b42e8a6c I made the font size dependant on browser dimensions, so this case should not happen anymore. Can you try ?

**Comment by dblanchet** [comment]
I tried with various zoom level. The problem seems to be fixed. The font is scaling so the code fits in the frame.

There is just one thing:

<img width="1113" alt="capture d ecran 2017-05-03 a 09 11 47" src="https://cloud.githubusercontent.com/assets/845542/25650940/81b9788a-2fe0-11e7-9f3d-4abc24003f44.png">

The progress bar and its label look a bit too big or is it just me?

**Comment by PierreQuentel** [comment]
You're right, this should be fixed in fae807f1b2881f9b205310c9d2140c56ad5fab28

**Comment by dblanchet** [comment]
I confirm it is fixed !

Thanks
