### ISSUE TITLE
Incorrect syntax highlight at the end of code block

### ISSUE THREAD

**Issue by dblanchet** [PierreQuentel/cours_python#6]
In slide 19 ("Test d'appartenance"), the final `False` is not colored the same way the previous occurences:

<img width="449" alt="capture d ecran 2017-02-27 a 15 06 14" src="https://cloud.githubusercontent.com/assets/845542/23364153/1e1c551e-fcfe-11e6-8242-aa87821214c1.png">

macOS 10.12.3, Firefox 51.0.1 and Chrome 56.0.2924.87

**Comment by PierreQuentel** [comment]
Syntax highlighting was changed in commit c9e7545ef0bb965c9c5db7727e7d4add2d218c7a so I think we can close this issue. Feel free to reopen it if necessary.

**Comment by dblanchet** [comment]
Fine, thanks.
